run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - deadcode
    - dupl
    - gofmt
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - structcheck
    - unused
    - varcheck

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/datatok/tintin
  dupl:
    threshold: 400
