version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "reindex.remote.whitelist=*:*"
      - reindex.ssl.verification_mode=none
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200

  pushgateway:
    image: prom/pushgateway:v1.3.0
    ports:
    - "9091:9091"

  prom:
    image: prom/prometheus:v2.19.0
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.retention=2h'
    - '--web.enable-lifecycle'
    volumes:
    - ./.ci/prom.yaml:/etc/prometheus/prometheus.yml:ro
    ports:
    - "9090:9090"

  app:
    #image: ghcr.io/datatok/tintin:main
    build: .
    environment:
    - AWS_REGION=us-east-1
    - TINTIN_PIPELINES_URL
    - TINTIN_PIPELINES_PATH=src/pipelines
    - HTML_TEMPLATE=/opt/tintin/index.html
    - LOG_LEVEL=debug
    - FRONT_URLS_PATH=/urls.yaml
    - GIT_SSL_NO_VERIFY=true
    - METRICS_LOG_API_URL=https://djobi-metrics-es.prod-steam.c5.par1.kube.qwant.ninja/
    volumes:
    - ./urls.yaml:/urls.yaml:ro
    - tmp:/tmp:rw
    - ./_dist/linux-amd64/tintin:/usr/local/bin/tintin:ro
    ports:
    - 8080:8080

volumes:
  tmp: